name: dkms_demo_multisig
description: Multisig demo for mobile devices using Keri bindings for Dart.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  keri: ^1.3.2
  asymmetric_crypto_primitives: ^0.4.5
  mobile_scanner: ^2.1.0
  path_provider: ^2.0.11
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
